services:
  flask:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./src/flask_postgresql_sample:/app
    depends_on:
      - postgresql
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgresql/postgres
  postgresql:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres 
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./for_develop/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - flask    
